/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import hospital.ModelEnfermedad;
import hospital.ModelUser;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author wilme
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() throws SQLException {
        initComponents();
        fillCombUsr();
        fillCombEnf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_selectp = new javax.swing.JLabel();
        select_user = new javax.swing.JComboBox<>();
        lb_enf = new javax.swing.JLabel();
        select_enf = new javax.swing.JComboBox<>();
        lb_obs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_obs = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_fecha_inicio = new javax.swing.JTextField();
        txt_fecha_final = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_addEnf = new javax.swing.JButton();
        btn_addUsr = new javax.swing.JButton();
        btn_updateUsr = new javax.swing.JButton();
        btn_updateEnf = new javax.swing.JButton();

        setTitle("Registro");
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);

        lb_title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lb_title.setText("Registrar Diagnóstico de Paciente");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_selectp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_selectp.setText("Paciente");

        select_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_userActionPerformed(evt);
            }
        });

        lb_enf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_enf.setText("Enfermedad");

        lb_obs.setText("Observaciones");

        jLabel1.setText("Fecha Hora de Ingreso");

        jLabel2.setText("Fecha Hora de Salida");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txt_obs.setViewportView(jTextArea1);

        btn_cancel.setText("Cancelar");

        btn_save.setText("Guardar");

        btn_addEnf.setText("+");
        btn_addEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEnfActionPerformed(evt);
            }
        });

        btn_addUsr.setText("+");
        btn_addUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUsrActionPerformed(evt);
            }
        });

        btn_updateUsr.setText("Actualizar");
        btn_updateUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateUsrActionPerformed(evt);
            }
        });

        btn_updateEnf.setText("Actualizar");
        btn_updateEnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateEnfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_title)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lb_obs)
                                        .addComponent(lb_selectp)
                                        .addComponent(lb_enf)
                                        .addComponent(select_user, 0, 420, Short.MAX_VALUE)
                                        .addComponent(select_enf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_addUsr)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_updateUsr))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_addEnf)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_updateEnf))))
                                .addComponent(txt_obs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_selectp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_enf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_enf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_addUsr)
                            .addComponent(btn_updateUsr))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_addEnf)
                            .addComponent(btn_updateEnf))))
                .addGap(18, 18, 18)
                .addComponent(lb_obs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha_final))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void select_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_userActionPerformed

    private void btn_addEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEnfActionPerformed
        // TODO add your handling code here:
        FormEnfermedad openForm = new FormEnfermedad();
        openForm.setVisible(true);
    }//GEN-LAST:event_btn_addEnfActionPerformed

    private void btn_updateEnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateEnfActionPerformed
        try {
            // TODO add your handling code here:
            fillCombEnf();
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateEnfActionPerformed

    private void btn_addUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUsrActionPerformed
        // TODO add your handling code here:
        FormUser openForm = new FormUser();
        openForm.setVisible(true);
    }//GEN-LAST:event_btn_addUsrActionPerformed

    private void btn_updateUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateUsrActionPerformed
        try {
            // TODO add your handling code here:
            fillCombUsr();
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateUsrActionPerformed

    //FILL COMBOBOX USERS
    public void fillCombUsr() throws SQLException{
        ResultSet rs = ModelUser.selectAllUser();
        select_user.removeAllItems();
        select_user.addItem("---Seleccionar---");
        while(rs.next()){
            select_user.addItem(rs.getString(5)+", "+rs.getString(7));
        }
    }
    
    //FILL COMBOBOX ENFERMEDADES
    public void fillCombEnf() throws SQLException{
        ModelEnfermedad connect = new ModelEnfermedad();
        connect.getConexion();
        ResultSet rs = ModelEnfermedad.selectAllEnfermedades();
        select_enf.removeAllItems();
        select_enf.addItem("---Seleccionar---");
        while(rs.next()){
            select_enf.addItem(rs.getString(2));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Registro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEnf;
    private javax.swing.JButton btn_addUsr;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_updateEnf;
    private javax.swing.JButton btn_updateUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_enf;
    private javax.swing.JLabel lb_obs;
    private javax.swing.JLabel lb_selectp;
    private javax.swing.JLabel lb_title;
    private javax.swing.JComboBox<String> select_enf;
    private javax.swing.JComboBox<String> select_user;
    private javax.swing.JTextField txt_fecha_final;
    private javax.swing.JTextField txt_fecha_inicio;
    private javax.swing.JScrollPane txt_obs;
    // End of variables declaration//GEN-END:variables
}
